# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nCTlNnC4ric8_2JUjRffQJjdoCp98pwO
"""

import webbrowser
import urllib.parse

# Define the search query
query = "Ethical Hacking Webinar"

# Encode the query for use in a URL
encoded_query = urllib.parse.quote(query)

# Create the Google search URL
url = f"https://www.google.com/search?q={encoded_query}"

# Open the URL in the default web browser
webbrowser.open(url)