# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nCTlNnC4ric8_2JUjRffQJjdoCp98pwO
"""

import os
from pathlib import Path

def list_files_and_folders(desktop_path):
    """List all files and folders in the specified directory."""
    items = [item for item in Path(desktop_path).iterdir() if item.is_file() or item.is_dir()]
    return items

def delete_item(item_path):
    """Delete the specified file or folder."""
    try:
        if item_path.is_file():
            item_path.unlink()  # Delete file
            print(f"Deleted file: {item_path.name}")
        elif item_path.is_dir():
            for child in item_path.iterdir():
                if child.is_file():
                    child.unlink()
                else:
                    delete_item(child)  # Recursively delete subdirectories
            item_path.rmdir()  # Delete the empty directory
            print(f"Deleted folder: {item_path.name}")
    except Exception as e:
        print(f"Error deleting {item_path.name}: {e}")

def main():
    # Get the user's desktop path
    desktop_path = Path.home() / "Desktop"
    print(f"Listing items in: {desktop_path}")

    items = list_files_and_folders(desktop_path)

    if not items:
        print("No files or folders found on the desktop.")
        return

    # Display items
    for item in items:
        print(f"- {item.name}")

    # User input for deletion
    filename = input("Enter the name of the file/folder you want to delete (or part of the name): ").strip()

    # Find items matching the filename
    matching_items = [item for item in items if filename in item.name]

    if not matching_items:
        print("No matching files or folders found.")
        return

    print("Matching items:")
    for index, item in enumerate(matching_items):
        print(f"{index + 1}: {item.name}")

    try:
        choice = int(input("Enter the number of the file/folder you want to delete (0 to exit): "))

        if choice == 0:
            print("Exiting without deleting.")
            return

        if 1 <= choice <= len(matching_items):
            item_to_delete = matching_items[choice - 1]
            confirm = input(f"Are you sure you want to delete '{item_to_delete.name}'? (yes/no): ").strip().lower()
            if confirm == 'yes':
                delete_item(item_to_delete)
            else:
                print("Deletion cancelled.")
        else:
            print("Invalid choice. Please enter a number from the list.")
    except ValueError:
        print("Please enter a valid number.")

if __name__ == "__main__":
    main()