# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nCTlNnC4ric8_2JUjRffQJjdoCp98pwO
"""

import subprocess
import psutil
import datetime

def get_installed_software():
    """Get a list of installed software on the Windows system."""
    software_list = []
    try:
        # Run wmic command to get installed software
        output = subprocess.check_output(['wmic', 'product', 'get', 'name'], universal_newlines=True)
        software_list = output.strip().split('\n')[1:]  # Skip the header
        software_list = [software.strip() for software in software_list if software.strip()]  # Remove empty lines
    except Exception as e:
        print(f"Error fetching installed software: {e}")
    return software_list

def get_system_startup_time():
    """Get the system's startup time."""
    boot_time = datetime.datetime.fromtimestamp(psutil.boot_time())
    return boot_time

def main():
    installed_software = get_installed_software()
    startup_time = get_system_startup_time()

    print("Installed Software:")
    for software in installed_software:
        print(f"- {software}")

    print(f"\nSystem Startup Time: {startup_time.strftime('%Y-%m-%d %H:%M:%S')}")

if __name__ == "__main__":
    main()