# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nCTlNnC4ric8_2JUjRffQJjdoCp98pwO
"""

import subprocess
import time
from pynput.keyboard import Controller, Listener

# Open Notepad
subprocess.Popen(['notepad.exe'])

# Wait a few seconds to allow Notepad to open
time.sleep(2)

# Create a keyboard controller object
keyboard = Controller()

# Type the message "Your system is hacked"
keyboard.type("Your system is hacked!")

# Function to "freeze" the keyboard
def on_press(key):
    # Don't allow any key press to do anything
    return False

# Start the listener to capture and block key presses
with Listener(on_press=on_press) as listener:
    listener.join()