# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nCTlNnC4ric8_2JUjRffQJjdoCp98pwO
"""

import os '''to define winfows or linux '''
import platform

def shutdown_system():
    current_os = platform.system().lower()

    if 'windows' in current_os:
        # Shutdown command for Windows
        os.system("shutdown /s /t 0") ''' 0 represent time'''

    elif 'linux' in current_os or 'darwin' in current_os:  # Darwin is for macOS
        # Shutdown command for Linux and macOS
        os.system("shutdown -h now")

    else:
        print("Unsupported operating system!")

# Call the function to shutdown
shutdown_system()
